---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - swap_management
    - snap_removal
  tasks:
    - name: Garantindo /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.1.100 kube-master
        - 172.16.1.101 kube-node1
        - 172.16.1.102 kube-node2
        - 172.16.1.103 kube-infra
        - 172.16.1.202 docker-registry

    - name: Cria o arquivo containerd.conf
      ansible.builtin.file:
        path: /etc/modules-load.d/containerd.conf
        state: touch

    - name: Configurando módulos
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
      with_items:
        - overlay
        - br_netfilter

    - name: Carregando módulos
      ansible.builtin.shell: modprobe overlay && modprobe br_netfilter

    - name: Cria o arquivo kubernetes.conf
      ansible.builtin.file:
        path: /etc/sysctl.d/kubernetes.conf
        state: touch

    - name: Configurando sysctl
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/kubernetes.conf
        line: "{{ item }}"
      with_items:
        - net.bridge.bridge-nf-call-ip6tables = 1
        - net.bridge.bridge-nf-call-iptables = 1
        - net.ipv4.ip_forward = 1

    - name: Aplicando sysctl
      ansible.builtin.shell: sysctl --system

    - name: Adiciona usuário suporte
      ansible.builtin.user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - mysql-client
        - nfs-common
        - git
        - vim

    - name: Clona repositório com os arquivos do curso para a HOME do usuário suporte
      ansible.builtin.git:
        repo: 'https://github.com/4linux/541-kubernetes.git'
        dest: /home/suporte/541

    - name: Adiciona repositório apt para versão estável
      ansible.builtin.deb822_repository:
        name: Docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_distribution_release }}"
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Instala o Containerd
      ansible.builtin.apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Criar conf default do Containerd
      ansible.builtin.shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

    - name: Ativa o Systemd no arquivo config.toml
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Ativa o uso de plugins no arquivo config.toml
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: '^disabled_plugins ='
        replace: '#disabled_plugins ='

    - name: Reinicia o containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: Adicione o repositório apt do Kubernetes
      ansible.builtin.deb822_repository:
        name: Kubernetes
        types: deb
        uris: https://pkgs.k8s.io/core:/stable:/v1.28/deb/
        suites: /
        signed_by: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        state: present

    - name: Instala os pacotes do Kubernetes
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl

    - name: Inicializa o cluster Kubernetes atraves da ferramenta kubeadm
      ansible.builtin.shell: kubeadm init --apiserver-advertise-address=172.16.1.100 --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all > /opt/init_cluster
      args:
        creates: /opt/init_cluster

    - name: Cria o diretório .kube para o usuário vagrant
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
        mode: '0755'

    - name: Configura o kubeconfig para o usuário vagrant
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes

    - name: Definir permissao de acesso ao arquivo config
      ansible.builtin.file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Cria o diretório .kube para o usuário suporte
      ansible.builtin.file:
        path: /home/suporte/.kube
        state: directory
        owner: suporte
        group: suporte
        mode: '0755'

    - name: Configura o kubeconfig para o usuário suporte
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/suporte/.kube/config
        remote_src: yes

    - name: Definir permissão de acesso ao arquivo config
      ansible.builtin.file:
        path: /home/suporte/.kube/config
        owner: suporte
        group: suporte
        mode: '0644'

    - name: Instala a rede calico no cluster
      become: false
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml

    - name: Permite que o master execute Pods como Worker
      become: false
      ansible.builtin.command: kubectl taint nodes kube-master node-role.kubernetes.io/control-plane-
      register: taint_result
      changed_when: taint_result.rc == 0
      failed_when: taint_result.rc != 0 and 'not found' not in taint_result.stderr

    - name: Gera o comando para o join de novos nodes
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command

    - name: Copia o comando do join no arquivo local
      ansible.builtin.copy:
        content: '{{ join_command.stdout_lines[0] }}\n'
        dest: '/vagrant/join-command'
