# SPDX-License-Identifier: GPL-3.0-only
---
# tasks file for swap_management

- name: Remove swap do arquivo /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disables swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb > 0

- name: Remove o arquivo de swap /swap.img
  ansible.builtin.file:
    path: /swap.img
    state: absent
